"""Auto-generated Database migration script

Revision ID: 671b59012a0e
Revises:
Create Date: 2017-10-05 18:02:20.715452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671b59012a0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=True),
        sa.Column('firstname', sa.String(length=10), nullable=False),
        sa.Column('lastname', sa.String(length=10), nullable=False),
        sa.Column('password_hash', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    op.create_table(
        'shoppinglists',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'],
                                onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'shoppinglist_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('shoppinglist_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['shoppinglist_id'], ['shoppinglists.id'],
                                onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppinglist_items')
    op.drop_table('shoppinglists')
    op.drop_table('users')
    # ### end Alembic commands ###
